### ISSUE TITLE
Building with 2.33.1 results in segfaults in aarch64

### ISSUE THREAD

**Issue by isuruf** [conda-forge/binutils-feedstock#21]
Eg:
https://cloud.drone.io/conda-forge/python-feedstock/57/1/2
https://cloud.drone.io/conda-forge/binutils-feedstock/33

**Comment by isuruf** [comment]
Fixed with #22

**Comment by jakirkham** [comment]
@jjhelmus @mingwandroid, do either of you have any idea why these segfaults might occur?

**Comment by jjhelmus** [comment]
According to [this commit](https://github.com/crosstool-ng/crosstool-ng/commit/36bb675a71cc66a2abd69bc82d613f2153d3791f) in the crosstools-ng repository, glibc requires a fix to work with binutils 2.30 or newer on aarch64.  My guess is that the segfauls are related to this but I have not been able to find more information on this issue.

**Comment by isuruf** [comment]
I think the issue is about the gcc version. When compiled with the compilers on the docker image (gcc 4.4), the segfaults go away.

**Comment by jjhelmus** [comment]
What binutils version is installed in the docker image?

**Comment by isuruf** [comment]
2.27

**Comment by jjhelmus** [comment]
Not sure if these are related but:

crosstools-ng has a [patch](https://github.com/crosstool-ng/crosstool-ng/blob/36bb675a71cc66a2abd69bc82d613f2153d3791f/packages/glibc/2.26/0001-aarch64-rewrite-elf_machine_load_address.patch) for glibc 2.26 that I believe is backported from 2.27.  That patch references https://sourceware.org/ml/binutils/2013-06/msg00248.html (binutils mailing list) which in turn links to https://sourceware.org/ml/libc-ports/2013-06/msg00043.html (glibc mailing list).
