### ISSUE TITLE
Installing conda binutils causes cmake to fail upon detection of C compiler

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/binutils-feedstock#6]
I tried with both binutils 2.27 and 2.28

```sh
Check for working C compiler: /home/sylvain/miniconda3/bin/cc -- broken
CMake Error at /home/sylvain/miniconda3/share/cmake-3.8/Modules/CMakeTestCCompiler.cmake:51 (message):
  The C compiler "/home/sylvain/miniconda3/bin/cc" is not able to compile a
  simple test program.
```

However, the system's binutils works perfectly, which is version 2.26.

I am using a salford systems' conda package for gcc-6.

**Comment by frol** [comment]
The latest binutils is 2.28. Have you tried it?

**Comment by SylvainCorlay** [comment]
Yes I meant 2.27 and 2.28. Fixed the description above.

**Comment by frol** [comment]
Unfortunately, I have no ideas why this happens and I have no free time at the moment to work on this. GCC and binutils are really tricky to package, especially, for portable use like conda envs. It might be helpful to read the detailed cmake log and try to reproduce the compilation error with bare gcc command or create a minimal reproduction cmake project.

**Comment by jakirkham** [comment]
Is this still an issue?

**Comment by isuruf** [comment]
Closing for now. If this is still an issue, please reopen
